### ISSUE TITLE
1.8 Builds fails on Linux / GCC 4.6: missing #include <stddef.h>

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#359]
Originally reported on Google Code with ID 356

```
What steps will reproduce the problem?
make
build with libunwind 0.99

What is the expected output? What do you see instead?
src/base/elf_mem_image.cc: In member function ‘void base::ElfMemImage::Init(const void*)’:
src/base/elf_mem_image.cc:251:3: error: ‘ptrdiff_t’ was not declared in this scope
src/base/elf_mem_image.cc:251:3: note: suggested alternatives:
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.6.1/../../../../include/c++/4.6.1/x86_64-unknown-linux-gnu/bits/c++config.h:156:28:
note:   ‘std::ptrdiff_t’
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.6.1/../../../../include/c++/4.6.1/x86_64-unknown-linux-gnu/bits/c++config.h:156:28:
note:   ‘std::ptrdiff_t’
src/base/elf_mem_image.cc:251:13: error: expected ‘;’ before ‘relocation’
src/base/elf_mem_image.cc:255:37: error: ‘relocation’ was not declared in this scope
make: *** [elf_mem_image.lo] Error 1

What version of the product are you using? On what operating system?
# uname -a
Linux Chobits 2.6.39-ARCH #1 SMP PREEMPT Sat Jul 9 14:57:41 CEST 2011 x86_64 AMD Athlon(tm)
II Dual-Core M340 AuthenticAMD GNU/Linux

gcc 4.6.1 from archlinux

Please provide any additional information below.
This issue is similar to http://code.google.com/p/google-perftools/issues/detail?id=301.
I added a #include <stddef.h> to src/base/elf_mem_image.h and it works.
```

Reported by `shellpick` on 2011-07-27 03:43:36
