### ISSUE TITLE
Doesn't build on Ubuntu 10.04: PR_SET_PTRACER

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#479]
Originally reported on Google Code with ID 476

```
What steps will reproduce the problem?
1. Build on Ubuntu 10.04.
2. Fails with the following error.

src/base/linuxthreads.cc: In function 'int ListAllProcessThreads(void*, int (*)(void*,
int, pid_t*, __va_list_tag*), ...)':
src/base/linuxthreads.cc:629: error: 'PR_SET_PTRACER' was not declared in this scope


What is the expected output? What do you see instead?
It should be built.


What version of the product are you using? On what operating system?
The latest r160.


Please provide any additional information below.
It looks introduced in r152 for the issue 437.  https://code.google.com/p/gperftools/source/detail?r=152

We may need to switch it with versions.
```

Reported by `dmikurube@chromium.org` on 2012-10-23 04:11:35
