### ISSUE TITLE
Can't build on OSX Sierra 10.12.6

### ISSUE THREAD

**Issue by ysolovyov** [gperftools/gperftools#910]
```
./autogen.sh
./configure
make
```
then getting
```
/usr/include/mach-o/dyld.h:230:13: note: '_dyld_present' has been explicitly marked deprecated here
extern bool _dyld_present(void)                                                              __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_1,__MAC_10_5,__IPHONE_NA,__IPHONE_NA);
            ^
1 warning generated.
mv -f benchmark/.deps/unwind_bench-unwind_bench.Tpo benchmark/.deps/unwind_bench-unwind_bench.Po
g++ -DHAVE_CONFIG_H -I. -I./src  -I./src   -D_THREAD_SAFE  -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation   -fno-builtin -g -O2 -MT benchmark/unwind_bench-getcontext_light.o -MD -MP -MF benchmark/.deps/unwind_bench-getcontext_light.Tpo -c -o benchmark/unwind_bench-getcontext_light.o `test -f 'benchmark/getcontext_light.cc' || echo './'`benchmark/getcontext_light.cc
In file included from benchmark/getcontext_light.cc:1:
/usr/include/ucontext.h:43:2: error: The deprecated ucontext routines require _XOPEN_SOURCE to be defined
#error The deprecated ucontext routines require _XOPEN_SOURCE to be defined
 ^
benchmark/getcontext_light.cc:4:34: error: unknown type name 'ucontext_t'
extern "C" void getcontext_light(ucontext_t *ctx);
                                 ^
benchmark/getcontext_light.cc:56:34: error: unknown type name 'ucontext_t'
extern "C" void getcontext_light(ucontext_t *ctx) {
                                 ^
3 errors generated.
make: *** [benchmark/unwind_bench-getcontext_light.o] Error 1
```

Xcode 8.3.3 is installed

```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by alk** [comment]
Thanks for reporting it. Simplest fix would be probably not building any benchmarks on osx. Unless someone could contribute a proper fix.

**Comment by alk** [comment]
I.e. something like this:

```
diff --git a/Makefile.am b/Makefile.am
index 811a9a7..7a191bc 100755
--- a/Makefile.am
+++ b/Makefile.am
@@ -856,6 +856,8 @@ endif WITH_STACK_TRACE
 endif WITH_DEBUGALLOC
 
 if !MINGW
+if !OSX
+
 noinst_LTLIBRARIES += librun_benchmark.la
 librun_benchmark_la_SOURCES = \
        benchmark/run_benchmark.c benchmark/run_benchmark.h
@@ -898,6 +900,8 @@ binary_trees_shared_SOURCES = benchmark/binary_trees.cc
 binary_trees_shared_CXXFLAGS = $(PTHREAD_CFLAGS) $(AM_CXXFLAGS) $(NO_BUILTIN_CXXFLAGS)
 binary_trees_shared_LDFLAGS = $(PTHREAD_CFLAGS) $(TCMALLOC_FLAGS)
 binary_trees_shared_LDADD = libtcmalloc_minimal.la $(PTHREAD_LIBS)
+
+endif !OSX
 endif !MINGW
 
 ### ------- tcmalloc (thread-caching malloc + heap profiler + heap checker)
```

**Comment by ysolovyov** [comment]
@alk thanks

**Comment by PiotrSikora** [comment]
@alk Thanks! However, only `unwind-bench` is broken.

**Comment by krlmlr** [comment]
`dyld_present()` seems to always return `true`: https://opensource.apple.com/source/dyld/dyld-519.2.2/dyld3/APIs_macOS.cpp.auto.html .
