### PR TITLE
fix compile failed while setting --disable-cpu-profiler

### PR DESCRIPTION
**Pull request by niukuo**
fix a compile error while setting --disable-cpu-profiler
introduced in f4aa2a435eed63fc047448635f705a9c6037bd97

> libtool: compile:  g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../gperftools -I./src -I../gperftools/src -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-result -fno-omit-frame-pointer -g -O2 -MT src/stacktrace.lo -MD -MP -MF src/.deps/stacktrace.Tpo -c ../gperftools/src/stacktrace.cc  -fPIC -DPIC -o src/.libs/stacktrace.o
In file included from ../gperftools/src/stacktrace_impl_setup-inl.h:70:0,
                 from ../gperftools/src/stacktrace.cc:128:
../gperftools/src/stacktrace_generic_fp-inl.h: In function 'int GetStackTraceWithContext_generic_fp(void**, int, int, const void*)':
../gperftools/src/stacktrace_generic_fp-inl.h:202:33: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
     auto uc = static_cast<const ucontext_t*>(ucp);
                                 ^
../gperftools/src/stacktrace_generic_fp-inl.h:202:33: error: expected '>' before 'ucontext_t'
../gperftools/src/stacktrace_generic_fp-inl.h:202:33: error: expected '(' before 'ucontext_t'
../gperftools/src/stacktrace_generic_fp-inl.h:202:33: error: 'ucontext_t' was not declared in this scope
../gperftools/src/stacktrace_generic_fp-inl.h:202:44: error: expected primary-expression before '>' token
     auto uc = static_cast<const ucontext_t*>(ucp);
                                            ^
../gperftools/src/stacktrace_generic_fp-inl.h:202:50: error: expected ')' before ';' token
     auto uc = static_cast<const ucontext_t*>(ucp);
                                                  ^

### CODE REVIEW

**Comment by alk** [comment]
I am sorry, I have somehow missed your patch. This work doesn't apply anymore. This code is reworked and I've tested it works with disabled cpu profiler
