### ISSUE TITLE
Compilation error for mipsel-32 

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#526]
Originally reported on Google Code with ID 523

```
What steps will reproduce the problem?
1../configure --host=mipsel-unknown-linux --prefix=/home/praneet/buildval CC=mipsel-unknown-linux-gnu-gcc
CXX=mipsel-unknown-linux-gnu-g++
2.make
3.

What is the expected output? What do you see instead?

I am trying to compile google-perftools for a mips-32 platform and I see the following
error. Attached are the complete logs for the configuration command used. It seems
that some how it is considering the platform for compilation as x86_64 and the instrucstion
set “lfence” is invalid for MIPS proecessor and hence this warning. Please let me know
if there is a work around for this issue


What version of the product are you using? On what operating system?
gperftools-2.0 version for google-perf tools

I am trying to build on system linux 2.6.32-33-generic #70-Ubuntu-SMP processor type
= x86_64

for target type mipsel-unknown-linux for MIPSR3000 32bit processor



Please provide any additional information below.

attached are complete console logs

```

Reported by `praneetchivate` on 2013-04-23 09:15:29

<hr>
- _Attachment: [gperflog](https://storage.googleapis.com/google-code-attachments/gperftools/issue-523/comment-0/gperflog)_
