### ISSUE TITLE
2.6 build failure on macOS: Undefined symbols for architecture x86_64:   "___lsan_ignore_object"

### ISSUE THREAD

**Issue by ilovezfs** [gperftools/gperftools#901]
Tested on macOS 10.10, 10.11, and 10.12.
```
libtool: link: /usr/bin/clang++ -D_THREAD_SAFE -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -fno-builtin -Os -w -pipe -march=native -mmacosx-version-min=10.11 -D_XOPEN_SOURCE -D_THREAD_SAFE -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -o malloc_bench benchmark/malloc_bench-malloc_bench.o  -L/usr/local/lib ./.libs/librun_benchmark.a ./.libs/libtcmalloc_minimal.a
Undefined symbols for architecture x86_64:
  "___lsan_ignore_object", referenced from:
      InitModule() in libtcmalloc_minimal.a(libtcmalloc_minimal_internal_la-malloc_extension.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [malloc_bench] Error 1
```
https://gist.github.com/ilovezfs/632b653999d975eef5e5da6e9a30925d

Seems to be a regression from https://github.com/gperftools/gperftools/commit/70a35422b5509a456584b132ad8ce4466af323ea.

https://github.com/Homebrew/homebrew-core/pull/15298
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4153/
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4153/version=sierra/consoleText
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4153/version=el_capitan/consoleText
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4153/version=yosemite/consoleText

**Comment by ilovezfs** [comment]
Seems to be a regression from https://github.com/gperftools/gperftools/commit/70a35422b5509a456584b132ad8ce4466af323ea.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/15298
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4153/
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4153/version=sierra/consoleText
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4153/version=el_capitan/consoleText
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4153/version=yosemite/consoleText

**Comment by ilovezfs** [comment]
CC @fjricci @alk

**Comment by fjricci** [comment]
I think this means we need to append AM_LDFLAGS to libtcmalloc_la_LDFLAGS after all

**Comment by fjricci** [comment]
I didn't realize travis doesn't test macOS builds, I'll put up a patch for that.

**Comment by ilovezfs** [comment]
@fjricci thanks!

**Comment by fjricci** [comment]
Actually this looks like a different issue, I think Makefile.in needs to be updated somehow, not sure how that works, just running ./configure doesn't seem to be sufficient.

**Comment by fjricci** [comment]
If I clean and re-run autogen.sh, the build works (just ./configure isn't sufficient though). A `git diff` reveals no differences, any ideas @alk?

**Comment by ilovezfs** [comment]
Note I tested with HEAD as well, running autoreconf -fiv, and same failure.

**Comment by ilovezfs** [comment]
https://gist.github.com/ilovezfs/71f7bb5b841c1116698eafa52835d7b2

**Comment by fjricci** [comment]
I can't build tcmalloc fully locally due to some system library configuration issues, but I think that this should take care of the __lsan_ignore_object problem, as it gets me almost all the way to a successful build: https://github.com/gperftools/gperftools/pull/902

Are you able to attempt a build off of a pull request?

**Comment by ilovezfs** [comment]
This has 902 applied: https://gist.github.com/ilovezfs/b77553dd9bf20c3744c2d782b7ac5deb

**Comment by fjricci** [comment]
Hrm okay. I'm not sure where to apply the flag such that it gets correctly added to all targets that depend on libtcmalloc. Hopefully @alk has input there.

**Comment by ilovezfs** [comment]
@fjricci I can cheat in the formula for now by doing this
```
diff --git a/Formula/gperftools.rb b/Formula/gperftools.rb
index 24132ed..9f50318 100644
--- a/Formula/gperftools.rb
+++ b/Formula/gperftools.rb
@@ -20,7 +20,7 @@ class Gperftools < Formula
   end
 
   def install
-    ENV.append_to_cflags "-D_XOPEN_SOURCE"
+    ENV.append_to_cflags "-D_XOPEN_SOURCE -Wl,-U,___lsan_ignore_object"
 
     system "autoreconf", "-fiv" if build.head?
     system "./configure", "--disable-dependency-tracking",
```
which does lead me to think the need to do `ENV.append_to_cflags "-D_XOPEN_SOURCE"` is a preexisting bug I hadn't noticed, to digress for a moment :)

**Comment by alk** [comment]
Ah, I should have checked the docs instead of plainly saying AM_LDFLAGS is auto-added. Sorry for that. Here is the doc with clear explanation: http://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html

So yes we need to be appending AM_LDFLAGS.

**Comment by fjricci** [comment]
#902 Works for me locally now. I'm not sure if there's a cleaner way

**Comment by ilovezfs** [comment]
Yes #902 works for me, too.

**Comment by alk** [comment]
Applied Francis' commit. Thanks all and apologies for causing this issue.

**Comment by alk** [comment]
A user reported that this still happens when linking libtcmalloc.a statically. Which is logical since osx needs this flag passed.

Is there any compile-time define used for static builds on OSX? I think it is best if we simply disable lsan feature in static builds by default.

**Comment by fjricci** [comment]
I actually think we could probably drop the lsan patches altogether. Sanitizer integration with custom allocators doesn't work well, and I don't for see it being fixed anytime soon.

**Comment by alk** [comment]
"lsan" commits have now been reverted.

**Comment by dtbartle** [comment]
Any chance you could cut a new release that includes the lsan reverts?

**Comment by alk** [comment]
I've just published 2.6.2. Apologies for delay.

**Comment by mingabc** [comment]
"swift build -Xswiftc -I/usr/local/opt/openssl/include -Xlinker -L/usr/local/opt/openssl/lib"   in Jenkins, it was fail, error log was  ---- 
Undefined symbols for architecture x86_64:
  "_ASN1_STRING_data", referenced from:
      _CNIOOpenSSL_ASN1_STRING_get0_data in SSLCertificate.swift.o
  "_ASN1_STRING_length", referenced from:
      __T010NIOOpenSSL22SubjectAltNameSequenceC4nextAA18OpenSSLCertificateC011AlternativeE0OSgyF in SSLCertificate.swift.o
  "_ASN1_STRING_to_UTF8", referenced from:
      __T010NIOOpenSSL18OpenSSLCertificateC10commonNameSays5UInt8VGSgyF in SSLCertificate.swift.o
  "_BIO_ctrl_pending", referenced from:
      __T010NIOOpenSSL13SSLConnectionC17getDataForNetwork3NIO10ByteBufferVSgAE0iJ9AllocatorV9allocator_tF in SSLConnection.swift.o
  "_BIO_free", referenced from:
      __T06Crypto7CRSAKeyC4makeAcA10RSAKeyTypeO4type_10Foundation4DataV4fromSb4x509tKFZ6$deferL_yyF in RSAKey.swift.o

**Comment by mingabc** [comment]
but i run the same command in  xcode and terminal was success
